# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAndAccess_App', '0002_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='Images/None/No-image.jpg', upload_to='Images'),
        ),
    ]
