# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAndAccess_App', '0003_auto_20170326_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(upload_to='http://127.0.0.1:8000/media/Images/'),
        ),
    ]
