# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAndAccess_App', '0004_auto_20170326_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
