# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAndAccess_App', '0005_auto_20170326_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(upload_to='UserAndAccess_App/media/Images'),
        ),
    ]
